### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by wajika** [denverdino/acr-login#7]
Run denverdino/acr-login@v10s
}
Run denverdino/acr-login@v1
  with:
    login-server: registry.cn-hangzhou.aliyuncs.com
    region-id: cn-hangzhou
    access-key-id: 
    access-key-secret: 
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@actions/core'
Require stack:
- /home/runner/work/_actions/denverdino/acr-login/v1/lib/login.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/denverdino/acr-login/v1/lib/login.js:21:27)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/work/_actions/denverdino/acr-login/v1/lib/login.js' ]
}

**Comment by denverdino** [comment]
Sorry for the incorrect version. The denverdino/acr-login@v0.1.0 should work

**Comment by denverdino** [comment]
https://github.com/denverdino/actions-test/blob/master/.github/workflows/main.yml

For your reference
